"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Events;
(function (Events) {
    Events["REQ_INIT"] = "REQ_INIT";
    Events["RES_OK_INIT"] = "RES_OK_INIT";
    Events["RES_ERR_INIT"] = "RES_ERR_INIT";
    Events["REQ_ADD_WIDGET"] = "REQ_ADD_WIDGET";
    Events["RES_OK_ADD_WIDGET"] = "RES_OK_ADD_WIDGET";
    Events["RES_ERR_ADD_WIDGET"] = "RES_ERR_ADD_WIDGET";
    Events["REQ_EDIT_WIDGET"] = "REQ_EDIT_WIDGET";
    Events["RES_OK_EDIT_WIDGET"] = "RES_OK_EDIT_WIDGET";
    Events["RES_ERR_EDIT_WIDGET"] = "RES_ERR_EDIT_WIDGET";
    Events["REQ_DELETE_WIDGET"] = "REQ_DELETE_WIDGET";
    Events["RES_OK_DELETE_WIDGET"] = "RES_OK_DELETE_WIDGET";
    Events["RES_ERR_DELETE_WIDGET"] = "RES_ERR_DELETE_WIDGET";
    Events["REQ_GET_WIDGET"] = "REQ_GET_WIDGET";
    Events["RES_OK_GET_WIDGET"] = "RES_OK_GET_WIDGET";
    Events["RES_ERR_GET_WIDGET"] = "RES_ERR_GET_WIDGET";
})(Events = exports.Events || (exports.Events = {}));
